# Generated by Django 4.2.4 on 2023-10-06 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100, null=True)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('edad_paciente', models.PositiveIntegerField(default=0)),
                ('sexo_paciente', models.CharField(max_length=10, null=True)),
                ('fecha_nac_paciente', models.DateField(default=None)),
                ('usuario_paciente', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('apellido_medico', models.CharField(max_length=100)),
                ('especialidad_medico', models.CharField(max_length=100)),
                ('usuario_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default='2023-01-01')),
                ('hora', models.TimeField(default='00:00')),
                ('motivo', models.CharField(max_length=200)),
                ('confirmado', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_app.paciente')),
            ],
        ),
    ]
