# Generated by Django 4.2.4 on 2023-10-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletarHsitorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('completada', models.BooleanField(default=True)),
                ('cita_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_app.citamedica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_app.paciente')),
            ],
        ),
    ]
