# Generated by Django 4.2.4 on 2023-10-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0002_completarhsitorial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletarHsitorial',
            new_name='CompletarHistorial',
        ),
    ]
