# Generated by Django 4.2.4 on 2023-10-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0004_remove_completarhistorial_completada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionesCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('leida', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas_app.citamedica')),
            ],
        ),
    ]
