# Generated by Django 4.2.4 on 2023-10-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_app', '0005_notificacionescita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificacionesCita',
        ),
    ]
